"""empty message

Revision ID: 34b11df3aae4
Revises: None
Create Date: 2016-07-16 13:15:52.719855

"""

# revision identifiers, used by Alembic.
revision = '34b11df3aae4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
